### ISSUE TITLE
Bitrate setting for Go+ Membership

### ISSUE THREAD

**Issue by Wombat1986** [danielvijge/SqueezeCloud#41]
Hi,
thanks for providing this easy-to-use plugin for LMS. Is it possible to set the bitrate for Go+ Membership? It always shows 128kbit MP3.
Thanks in advance and Regards,
Wombat

**Comment by xvluny** [comment]
I would also be very interested. Is there any progress on this?

**Comment by danielvijge** [comment]
Are you sure it is not already playing at a higher bitrate? The `128kbps, MP3 (SoundCloud)` that is shown in the web interface is [hardcoded](https://github.com/danielvijge/SqueezeCloud/blob/fee72f279db0f42542137b8a7f5a53fa7a506fd7/ProtocolHandler.pm#L85), and might not be the actual bitrate that is playing. Clicking on the title in the web interface might shown you the actual bitrate (but not 100% sure about it).

I don't have a SoundCloud subscription, so no way to test it. But in the API there nothing for this. A request to is made to [/tracks/TRACK_ID/stream](https://developers.soundcloud.com/docs/api/guide#playing), and this redirects to the actual streamable URL. I would suspect it's then up to SoundCloud to redirect members to a different URL that non-paying visitors.

**Comment by xvluny** [comment]
Hi, I have been unable to find the bitrate in the soundcloud web interface (might be that I am blind). However, I have been trying in a few tracks with squeezelite in debug mode.

The header when I begin streaming from soundcloud looks like this, stating 128 kbit
HTTP/1.1 206 Partial Content
Content-Type: audio/mpeg
Content-Length: 3934666
Connection: close
Date: Wed, 01 Nov 2023 09:26:35 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Access-Control-Max-Age: 3000
Last-Modified: Wed, 16 Nov 2016 16:16:44 GMT
ETag: "64fb556b8838eed61660a4c33d4c1853"
x-amz-storage-class: INTELLIGENT_TIERING
x-amz-server-side-encryption: AES256
x-amz-meta-bitrate: 128
x-amz-meta-duration: 245939
x-amz-meta-job: kGmmErlJoy3C
Cache-Control: max-age=252460800
x-amz-version-id: sQiGiB8YBWMCsQ2RKai3MdBlZEWVpcvk
Accept-Ranges: bytes
Server: AmazonS3
Content-Range: bytes 0-3934665/3934666
X-Cache: Miss from cloudfront
Via: 1.1 218c6128df18321f9758e53ccc351448.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: FRA60-P6
X-Amz-Cf-Id: NopdSV4I_MF8VVcYGCRk3HNIWhep5h3NTpdR_CXX1jWGAJdRprC-mw==

**Comment by danielvijge** [comment]
If SoundCloud doesn't already handle this automatically, and there is nothing in the API to trigger a higher bitrate for subscribers, there's not really anything I can do. Unless there is some documentation anywhere how to handle this, I have to close this issue as "not possible".

**Comment by ericpapaluca** [comment]
Hi @danielvijge - first off thanks for your work writing this plugin and the mixcloud plugin!

This issue is really bothering me, as I would gladly pay SoundCloud for HQ Streaming.  I've signed up and done some digging into how HQ streaming works on the front end, and it looks like something I may be able to replicate if I can grab the OAuth token from my browser session.

I'm investigating how to get playback to work and facing a similar issue [here](https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1699393-some-aac-files-result-in-error-decoder-does-not-support-file-format-code-0)
(which I think was you?)

However, I know the MixCloud plugin now uses `yt-dlp` in order to facilitate the retrieval and streaming (I think to circumvent this problem). My additional research shows that `yt-dlp` can also download HQ streams using the OAuth token, so I'm investigating how the MixCloud plugin works.

That said, I am very very new to Perl and not fully grasping what the plugin does and how it works. Would you be able to explain the main methods that are called for stream retrieval/playback and if there's any, some documentation on how the plugin works in general? I am very interested in solving this problem and contributing this back to the project if suitable.

Thanks for taking the time to read :)

**Comment by danielvijge** [comment]
The thread you link to on the forums is indeed by me. I encountered that while working on the Mixcloud plugin with `yt-dlp`. This was really related to decoding done by the server, and not something I could have ever fixed. And really cool that philippe_44 could fix it so quickly.

Comparing the Soundcloud and Mixcloud plugins, there is a pretty big difference. Soundcloud has an official API to stream tracks, whereas Mixcloud only has an API to retrieve information but not the actual stream. That's why Mixcloud has to use `yt-dlp` to get the track stream. It was using different online services in the past to do the same thing, but after a while they would break. Using an official API is much more stable, so if Mixcloud had an API to stream tracks, I would surely use that. That also implies I'm not a big fan of also using `yt-dlp` for the Soundcloud plugin, as I rather keep it simple and only use the official API.

I also don't really like (or maybe better: fully understand) Perl, but hopefully I can explain a bit how the Soundcloud plugin retrieves the stream:
- Plugins must define a protocol handler that implements some defined functions. One such function is [`getNextTrack()`](https://github.com/danielvijge/SqueezeCloud/blob/0.15/ProtocolHandler.pm#L187). This function is called when the user plays a Soundcloud track. This has the "fake" url soundcloud://12345678, with the number being the track's ID.
- Within this function it makes a call to the Soundcloud [API to get the track information](https://developers.soundcloud.com/docs/api/explorer/open-api#/tracks/get_tracks__track_id_).
- If the call is successful, the result of the API call is used to call [`gotNextTrack()`](https://github.com/danielvijge/SqueezeCloud/blob/0.15/ProtocolHandler.pm#L123)
- Within that function a call is made to [`getStreamURL()`](https://github.com/danielvijge/SqueezeCloud/blob/0.15/ProtocolHandler.pm#L96). This just takes the `stream_url` attribute from the JSON result of the API call.
- The final part is that the stream URL is done yet the direct URL, but an HTTP 301 redirect is performed by Soundcloud. So the [stream url is requested](https://github.com/danielvijge/SqueezeCloud/blob/0.15/ProtocolHandler.pm#L157) and then the `location` header is extracted. This is the final URL that can be stream directly. By setting [`$song->streamUrl($redirector);`](https://github.com/danielvijge/SqueezeCloud/blob/0.15/ProtocolHandler.pm#L169) it tells the player to stream that URL.

All the rest of the code is mainly to handle metadata.

**Comment by ericpapaluca** [comment]
Thanks for the information and explanation @danielvijge, it is very much appreciated and very helpful indeed. I'm going to start today to see if I can get some sort of version of hq streaming via the api-v2 today. I will post back here eventually if I'm able to do it.

**Comment by ericpapaluca** [comment]
Hi all!

Been a very long time since my last post (life gets in the way).. 

But I do have a fork of this project that enables 256kbps AAC working in Lyrion which can be found here:
https://github.com/ericpapaluca/SqueezeCloud

I've tested this and it works quite well and falls back to Daniel's flow whenever it fails.

Full disclosure (which is documented in the README): everything is completely vibe coded using Claude Code/Opus 4.8 - I used the Music Assistant implementation as a base and due to my lack of Perl-fu, let Claude run wild. 

It still requires you to get your OAuth token from a web session, which will expire so something to be aware of if you end up back on standard quality.

Hopefully this ends up being helpful to someone - main and massive credit goes to the masterminds that made this plugin and the python implementations
