### ISSUE TITLE
playback does not work anymore

### ISSUE THREAD

**Issue by polrus** [danielvijge/SqueezeCloud#42]
Hi
Thanks for this great plugin.
It had been working well for months. Suddenly it has stopped working.

i think soundcloud changed something. So I can see the list of my soundcloud collection and favourites but I cannot play. Nothing happens.

Ps. your plugin is not called squeecloud but sound cloud plugin so it may be confusing for ppl tring to follow github description and install instruction 
![obraz](https://user-images.githubusercontent.com/9408405/189620746-55517fed-5686-4bbe-a599-fcb3319b3e4c.png)

**Comment by danielvijge** [comment]
In a quick test playing still works for me. Do you still experience this issue? If so can you post debug logs?

With regards to the SqueezeCloud/SoundCloud name, that was sort-of intentional at one point. The plugin that I forked was called SqueezeCloud, so that name was kept. But it enabled the SoundCloud service, so that's why that name is shown in the menu. So before installation you would see SqueezeCloud (the plugin name), after installation SoundCloud (the service it enables).

**Comment by polrus** [comment]
there is the soundcloud plugin debug
https://cloud.inicio.pl/index.php/s/asdLaPB7fADrEwT
what is strange is that it seams to start playing but remains at 00:00 with no errors
![obraz](https://user-images.githubusercontent.com/9408405/190093431-060b54d0-7606-4cc1-bc97-e48b730633a0.png)

**Comment by danielvijge** [comment]
Only strange part I can see is
`[22-09-14 09:41:15.0809] Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Slim::Networking::Slimproto::client_readable: Can't locate object method "protocolHandler" via package "Slim::Player::SongStreamController" at /usr/share/perl5/Slim/Networking/Slimproto.pm line 622.
; fh=IO::Socket::INET=GLOB(0x4ee20e8)`
Although it doesn't specifically say that it cannot load the protocolHandler of SqueezeCloud, it would explain it, as this part of the code is responsible for the actual playing.
Did you modify the file in any way, that could cause it to be an invalid Perl file? Otherwise you might want to try uninstalling the plugin, then reinstalling it again.

**Comment by polrus** [comment]
Very strange - I discovered it works on other players connecting to the same squeezeserver but does not work on the one I use the most :)  - i'll investigate

**Comment by polrus** [comment]
I have the anwer.
This issue is related with squeezeplay-pulseaudio version 1.9.8 on Rpi (raspberry pi) Debian based Libreelec/Openelec binary.

Updating to squeezeplay 1.9.9 solves the problem 
you can get the source and binaries from
https://sourceforge.net/projects/lmsclients/files/squeezelite/linux/
